# Partie générale du site
homepage:
    path:  /
    defaults: { _controller: "LcdpFrontBundle:Home:index" }

menu_left:
    path:  /menu-left
    defaults: { _controller: "LcdpFrontBundle:Home:menuLeft" }

menu_right:
    path:  /menu-righ
    defaults: { _controller: "LcdpFrontBundle:Home:menuRight" }

front_page:
    path: /page/{slug}
    defaults: { _controller: "LcdpFrontBundle:Page:view" }

front_events:
    path: /evenements
    defaults: { _controller: "LcdpFrontBundle:Events:list" }

front_event:
    path: /evenement/{slug}
    defaults: { _controller: "LcdpFrontBundle:Events:view" }

front_news:
    path: /actualite/{slug}
    defaults: { _controller: "LcdpFrontBundle:News:view" }

front_albums:
    path: /albums
    defaults: { _controller: "LcdpFrontBundle:Album:list" }

front_album:
    path: /album/{slug}
    defaults: { _controller: "LcdpFrontBundle:Album:view" }