<?php

namespace Lcdp\CommonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{

    /**
     * Permet de lister tous les albums du site
     *
     * @param array $filters Tableau contenant les filtres
     * @param array $orders  Tableau contenant les tris
     * @param array $limit   Tableau contenant les limites
     *
     * @return array
     * @author André Tapia <contact@andretapia.com>
     */
    public function getList($filters = null, $orders = null, $limit = null)
    {
        $query = $this->createQueryBuilder('a')
                ->where('a.isDeleted = 0');

        if (!empty($filters)) {
            if (isset($filters['title']) && !empty($filters['title'])) {
                $query->andWhere('a.title LIKE :title');
                $query->setParameter('title', '%' . $filters['title'] . '%');
            }
            if (isset($filters['is_published']) && in_array($filters['is_published'], array('0', '1'))) {
                $query->andWhere('a.isPublished = :published');
                $query->setParameter('published', $filters['is_published']);
            }
        }

        if (!empty($orders)) {
            if (isset($orders['publication'])) {
                $query->orderBy('a.publicatedAt', $orders['publication']);
            }
        }

        if (!empty($limit)) {
            if (isset($limit['limit'])) {
                $query->setMaxResults($limit['limit']);
            }
        }

        $return = $query->getQuery()->getArrayResult();

        return $return;
    }
}
