<?php

namespace Lcdp\CommonBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{

    /**
     * Permet de lister toutes les pages éditable du site
     *
     * @param array $filters Tableau contenant les filtres
     * @return array
     * @author André Tapia <contact@andretapia.com>
     */
    public function getList($filters)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.isDeleted = 0')
            ->orderBy('p.position');

        if (!empty($filters)) {

            if (isset($filters['title']) && !empty($filters['title'])) {
                $query->andWhere('p.title LIKE :title');
                $query->setParameter('title', '%' . $filters['title'] . '%');
            }
            if (isset($filters['isPublished']) && in_array($filters['isPublished'], array('0', '1'))) {
                $query->andWhere('p.isPublished = :published');
                $query->setParameter('published', $filters['isPublished']);
            }
        }

        $return = $query->getQuery()->getArrayResult();

        return $return;
    }
}
