# Partie générale du site
homepage:
    pattern:  /
    defaults: { _controller: LcdpFrontBundle:Home:index }

contact_us:
    pattern: /contact
    defaults: { _controller: LcdpFrontBundle:Contact:index }

all_events:
    pattern: /evenements
    defaults: { _controller: LcdpFrontBundle:Events:list }

# Section "Le club"
club_histoire:
    pattern: /le-club/histoire
    defaults: { _controller: LcdpFrontBundle:Club:staticPage, contentId: 1 }

club_organigramme:
    pattern: /le-club/organigramme
    defaults: { _controller: LcdpFrontBundle:Club:organigram }

club_infos:
    pattern: /le-club/infos
    defaults: { _controller: LcdpFrontBundle:Club:staticPage, contentId: 2 }

# Section "Danse"
danse_all_news:
    pattern: /danse/actualites
    defaults: { _controller: LcdpFrontBundle:News:list, sectionId: 21 }

danse_news:
    pattern: /danse/actualites/{slug}
    defaults: { _controller: LcdpFrontBundle:News:show, sectionId: 21 }

danse_all_soiree:
    pattern: /danse/soirees
    defaults: { _controller: LcdpFrontBundle:News:list, sectionId: 22 }

danse_soiree:
    pattern: /danse/soirees/{slug}
    defaults: { _controller: LcdpFrontBundle:News:show, sectionId: 22 }

danse_all_event:
    pattern: /danse/evenements
    defaults: { _controller: LcdpFrontBundle:Events:list, sectionId: 23 }

danse_event:
    pattern: /danse/evenements/{slug}
    defaults: { _controller: LcdpFrontBundle:Events:show, sectionId: 23 }

danse_cours:
    pattern: /danse/cours
    defaults: { _controller: LcdpFrontBundle:Club:staticPage, contentId: 7 }

danse_infos:
    pattern: /danse/infos
    defaults: { _controller: LcdpFrontBundle:Club:staticPage, contentId: 7 }

# Section "Football"
foot_all_news:
    pattern: /football/actualites
    defaults: { _controller: LcdpFrontBundle:News:list, sectionId: 31 }

foot_news:
    pattern: /football/actualites/{slug}
    defaults: { _controller: LcdpFrontBundle:News:show, sectionId: 31 }

foot_all_event:
    pattern: /football/evenements
    defaults: { _controller: LcdpFrontBundle:Events:show, sectionId: 33 }

foot_event:
    pattern: /football/evenements/{slug}
    defaults: { _controller: LcdpFrontBundle:Events:show, sectionId: 33 }

# Section "Associtation"
assoc_all_soiree:
    pattern: /association/soirees
    defaults: { _controller: LcdpFrontBundle:News:list, sectionId: 11 }

assoc_soiree:
    pattern: /association/soirees/{slug}
    defaults: { _controller: LcdpFrontBundle:News:show, sectionId: 11 }

assoc_all_event:
    pattern: /association/evenements
    defaults: { _controller: LcdpFrontBundle:Events:list, sectionId: [11, 12, 13] }

assoc_event:
    pattern: /association/evenements/{slug}
    defaults: { _controller: LcdpFrontBundle:Events:show, sectionId: [11, 12, 13] }

assoc_all_sortie:
    pattern: /association/sorties
    defaults: { _controller: LcdpFrontBundle:News:list, sectionId: 12 }

assoc_sortie:
    pattern: /association/sorties/{slug}
    defaults: { _controller: LcdpFrontBundle:News:show, sectionId: 12 }

assoc_all_voyage:
    pattern: /association/voyages
    defaults: { _controller: LcdpFrontBundle:News:list, sectionId: 13 }

assoc_voyage:
    pattern: /association/voyages/{slug}
    defaults: { _controller: LcdpFrontBundle:News:show, sectionId: 13 }