# Partie générale du site
homepage:
    path:  /
    defaults: { _controller: "LcdpFrontBundle:Home:index" }
    options:
        sitemap: true

feed_news:
    path:  /feed/news
    defaults: { _controller: "LcdpFrontBundle:Feed:newsFeed" }

feed_events:
    path:  /feed/events
    defaults: { _controller: "LcdpFrontBundle:Feed:eventsFeed" }

menu_left:
    path:  /menu-left
    defaults: { _controller: "LcdpFrontBundle:Home:menuLeft" }

menu_right:
    path:  /menu-righ
    defaults: { _controller: "LcdpFrontBundle:Home:menuRight" }

front_page:
    path: /page/{slug}
    defaults: { _controller: "LcdpFrontBundle:Page:view" }

front_events:
    path: /evenements
    defaults: { _controller: "LcdpFrontBundle:Events:list" }
    options:
        sitemap: true

front_event:
    path: /evenement/{slug}
    defaults: { _controller: "LcdpFrontBundle:Events:view" }

front_news:
    path: /actualite/{slug}
    defaults: { _controller: "LcdpFrontBundle:News:view" }

front_albums_years:
    path: /albums
    defaults: { _controller: "LcdpFrontBundle:Album:listAlbumYears" }
    options:
        sitemap: true

front_albums:
    path: /albums/{year}
    defaults: { _controller: "LcdpFrontBundle:Album:listAlbums" }
    requirements:
        year: "\d+"

front_albums_groups:
    path: /albums/{year}/{album}
    defaults: { _controller: "LcdpFrontBundle:Album:listAlbumGroups" }
    requirements:
        year: "\d+"

front_album_view:
    path: /albums/{year}/{albumSlug}/groupe/{groupId}
    defaults: { _controller: "LcdpFrontBundle:Album:view" }
    requirements:
        year: "\d+"
        groupId: "\d+"

front_volunteer:
    path: /tous-benevoles/{slug}
    defaults: { _controller: "LcdpFrontBundle:Volunteer:view" }