lcdp_admin_homepage:
    path:  /
    defaults: { _controller: LcdpAdminBundle:Admin:index }

logout:
    path:   /logout
    defaults:  { _controller: LcdpAdminBundle:Security:logout }

login:
    path:   /login
    defaults:  { _controller: LcdpAdminBundle:Security:login }

login_check:
    path:   /login_check

#lcdp_admin_members:
#    path:  /membres
#    defaults: { _controller: LcdpAdminBundle:Member:memberList }
#
#lcdp_admin_member_edit:
#    path:  /membres/edition/{id}
#    defaults: { _controller: LcdpAdminBundle:Member:memberEdit, id: null }
#    requirements:
#        id: "\d+"
#
#lcdp_admin_newsletter:
#    path:  /newsletter
#    defaults: { _controller: LcdpAdminBundle:Newsletter:index }
#
#lcdp_admin_parameters:
#    path:  /parametrages
#    defaults: { _controller: LcdpAdminBundle:Admin:config }

lcdp_admin_page:
    path:  /pages
    defaults: { _controller: LcdpAdminBundle:Page:list }

lcdp_admin_page_edit:
    path:  /page/edition/{id}
    defaults: { _controller: LcdpAdminBundle:Page:edit, id: null }
    requirements:
        id: "\d+"

lcdp_admin_page_update:
    path:  /page/update/
    defaults: { _controller: LcdpAdminBundle:Page:updatePosition }
    methods: [POST]
    options:
        expose: true

lcdp_admin_news:
    path:  /news
    defaults: { _controller: LcdpAdminBundle:News:list }

lcdp_admin_news_edit:
    path:  /news/edition/{id}
    defaults: { _controller: LcdpAdminBundle:News:edit, id: null }
    requirements:
        id: "\d+"

lcdp_admin_events:
    path:  /events
    defaults: { _controller: LcdpAdminBundle:Event:list }

lcdp_admin_event_edit:
    path:  /event/edition/{id}
    defaults: { _controller: LcdpAdminBundle:Event:edit, id: null }
    requirements:
        id: "\d+"

lcdp_admin_content_soft_delete:
    path:  /remove/{content}/{id}
    defaults: { _controller: LcdpAdminBundle:Content:softDelete, id: null }
    requirements:
        id: "\d+"
        content: Page|News|Member|Event|Album|Volunteer

lcdp_admin_content_publish_content:
    path:  /publication/{status}/{content}/{id}
    defaults: { _controller: LcdpAdminBundle:Content:publishContent, id: null }
    requirements:
        id: "\d+"
        status: 0|1
        content: Page|News|Member|Event|Album|Volunteer

lcdp_admin_albums:
    path:  /albums
    defaults: { _controller: LcdpAdminBundle:Album:list }

lcdp_admin_album_edit:
    path:  /albums/edition/{id}
    defaults: { _controller: LcdpAdminBundle:Album:edit, id: null }
    requirements:
        id: "\d+"

lcdp_admin_remove_picture:
    path:  /albums/{albumId}/image/{id}
    defaults: { _controller: LcdpAdminBundle:Album:removeAlbumPicture }
    methods: [POST]
    options:
        expose: true

lcdp_admin_volunteers:
    path:  /volunteers
    defaults: { _controller: LcdpAdminBundle:Volunteer:list }

lcdp_admin_volunteer_edit:
    path:  /volunteer/edition/{id}
    defaults: { _controller: LcdpAdminBundle:Volunteer:edit, id: null }
    requirements:
        id: "\d+"